### ISSUE TITLE
Test boundary overrun still throws exception

### ISSUE THREAD

**Issue by roryprimrose** [roryprimrose/Neovolve.Logging.Xunit#296]
In an async Task test, the following exception was thrown:

```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.AggregateException: An error occurred while writing to logger(s). (There is no currently active test.)
 ---> System.InvalidOperationException: There is no currently active test.
   at Xunit.Sdk.TestOutputHelper.QueueTestOutput(String output) in /_/src/xunit.execution/Sdk/Frameworks/TestOutputHelper.cs:line 61
   at Neovolve.Logging.Xunit.TestOutputLogger.WriteLog(LogLevel logLevel, EventId eventId, String message, Exception exception)
   at Neovolve.Logging.Xunit.TestOutputLogger.WriteLogEntry[TState](LogLevel logLevel, EventId eventId, TState state, String message, Exception exception, Func`3 formatter)
   at Neovolve.Logging.Xunit.FilterLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|14_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Neovolve.Logging.Xunit.CacheLogger.WriteLogEntry[TState](LogLevel logLevel, EventId eventId, TState state, String message, Exception exception, Func`3 formatter)
   at Neovolve.Logging.Xunit.FilterLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass10_0`1.<Define>g__Log|0(ILogger logger, T1 arg1, Exception exception)
```

The existing try/catch should catch any exception rather than just InvalidOperationException.

**Comment by roryprimrose** [comment]
In this case, the exception was thrown because the logging configuration allowed it
